### ISSUE TITLE
NUnit 3 with Selenium grid 2 integration

### ISSUE THREAD

**Issue by vigneshwar-v** [nunit/dev#4]
I use Nunit 3's parallelizable attribute on each test fixtures, which works pretty good.
But still when I run my testcases on selenium grid via 2 nodes, the same is not happening and the run behaviour gets changed to sequential.

Do you have any comment on this??

**Comment by CharliePoole** [comment]
Someone who knows Selenium may need to comment on this. You will get more of an audience if you post the question on the nunit-discuss list. If you really prefer to file a bug report - that's what this is - it would be best to file it on the nunit project. This repository contains the wiki used by NUnit developers for our internal procedures.

Additionally, sample code always helps in posting about such problems.
