### ISSUE TITLE
confusing space formatting in visual studio settings file

### ISSUE THREAD

**Issue by MSK61** [nunit/dev#5]
I've tested the space formatting settings in the visual studio settings file in this repo in VS2010, VS2013, and VS2015 and have noticed that it causes a line like this

	if (x == 5) x = 3;
to be formatted as

	if( x == 5 ) x = 3;
Note the suppressed space between if keyword and the open parenthesis and the added inner spaces between the parentheses. This's in contrast with what's mentioned here https://github.com/nunit/nunit/blob/master/CONTRIBUTING.md.
 
Are you sure this formatting style in the settings file is intended?

**Comment by CharliePoole** [comment]
A bit of confusion about what "this repo" means. You filed this issue against the nunit/dev repo, which doesn't have any code but the link you give is to the nunit/nunit repo CONTRIBUTING file.

No need to re-file this elsewhere, but please just point to the settings file you are questioning.

**Comment by MSK61** [comment]
Sorry for confusion. The settings file I mean is this one https://github.com/nunit/dev/blob/master/nunit.vssettings. The other link I posted earlier is correct as it explains the rules for using spaces, which should reflect into the settings file.

**Comment by CharliePoole** [comment]
@MSK61 I suggest you use the settings file from the nunit repo for now.

@rprouse Should we maintain this settings file in the dev repo or just point the reference in the coding standard to the one in the NUnit repo?

**Comment by MSK61** [comment]
Seems I can't find a settings file in the nunit repo https://github.com/nunit/nunit, would appreciate if someone can point me to it.

**Comment by CharliePoole** [comment]
Sorry but you are right. I have one locally and I thought it was in the repo. @rprouse is their any reason not to have this in the nunit repo itself rather than dev?

**Comment by rprouse** [comment]
I originally put it here because it applies to all NUnit source, not just the main repo. It also has to be imported, so it will not automatically get used like the Rebracer settings we have in each repository.

I also expect that the [Rebracer ](https://visualstudiogallery.msdn.microsoft.com/410e9b9f-65f3-4495-b68e-15567e543c58) and [editorconfig ](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328) files are more up to date than the settings file. I work on many project with many formatting rules, so I keep those files up to date to auto-switch settings for the code I am working on.

Personally, I think those extensions are the best option for developers coming onto the project unless they use Resharper, we have a dotsettings file in the repo for that.

**Comment by rprouse** [comment]
I am fine with moving the settings file to the main repo. Before we do, we should fix inconsistencies and also compare recent NUnit code to both the settings and the standard.

**Comment by CharliePoole** [comment]
A further note... I hope to be rid of this repo before I go on vacation. The Code Standard page is copied to the docs repo, but I think the link probably still points to dev.

**Comment by CharliePoole** [comment]
An idea: any files that need to be imported or otherwise activated in VS should probably have a comment in them that says so. The documentation should explain how to do it as well.

**Comment by CharliePoole** [comment]
@MSK61 if you are interested in contributing, we'd be glad to have a fix for this file. :-)

**Comment by rprouse** [comment]
I guess that information should probably go in the developer docs. Maybe a new document under the developer FAQ? Something like Prerequisites? We could cover developing on Windows and Linux including setup and importing of settings.

The link from [CONTRIBUTING.md](https://github.com/nunit/nunit/blob/master/CONTRIBUTING.md) to the dev wiki also needs to be updated.

**Comment by CharliePoole** [comment]
Why not on the Coding Standard page itself? At least for now. The developer FAQ is pretty lame at the moment, I'm hoping to do some work on it as I travel.

**Comment by MSK61** [comment]
@CharliePoole My pleasure. I plan to have a look at it in the next couple of days, and I'll push my changes into the same file in its current dev repo(; I'm hardly following the discussion about distributing files between the dev repo and other repos.).

@rprouse Mentioning Rebracer and editorconfig(first time for me to hear about them), it might be a good idea to add a hint about them(at least that they exist) in the developer docs.

**Comment by CharliePoole** [comment]
@rprouse Can we close this issue? Should we move the vssettings file to the docs repo?
