### ISSUE TITLE
Console Runner Output Specification Unclear

### ISSUE THREAD

**Issue by blachniet** [nunit/dev#6]
The [Output Specification Format](https://github.com/nunit/dev/wiki/Command-Line-Options#output-specification-format) section of the console runner page does not clearly show how to format the `--result` option. The console runner help provides a clearer description:

```
      ...A SPEC may take one of
      the following forms:
          --OPTION:filename
          --OPTION:filename;format=formatname
          --OPTION:filename;transform=xsltfile
```

**Comment by CharliePoole** [comment]
The dev wiki covers works in progress and has some old specs for stuff that has already been built. You should be using the docs wiki for documentation about NUnit.

Please take a look at https://github.com/nunit/docs/wiki/Console-Command-Line and let me know if that seems clearer. I believe it matches the console runner help at this point.

We are in the process of removing the dev wiki stuff, but need to look at each page to ensure nothing is missed. If a link somewhere took you to it, please let us know that as well.

**Comment by blachniet** [comment]
I'm sorry, I'm not sure how I wound up there. If I figure out which link to me to the dev wiki, I will let you know.
